import { useState, useEffect } from 'react';
import axios from 'axios';

function Exam() {
  const [questions, setQuestions] = useState([]);
  const [previousQuestions, setPreviousQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingPrevious, setLoadingPrevious] = useState(false);
  const [error, setError] = useState(null);
  const [generatedAt, setGeneratedAt] = useState(null);
  const [nextUpdateTime, setNextUpdateTime] = useState(null);
  const [selectedDate, setSelectedDate] = useState(null);
  const [isFromCache, setIsFromCache] = useState(false);

  const today = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  // Get the next 4 AM IST timestamp
  const getNextFourAMIST = () => {
    const now = new Date();
    const currentIST = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
    
    // Create next 4 AM IST
    const nextFourAM = new Date(currentIST);
    nextFourAM.setHours(0, 0, 0, 0);
    
    // If current IST time is after 4 AM, use tomorrow's 4 AM
    if (currentIST.getHours() >= 4) {
      nextFourAM.setDate(nextFourAM.getDate() + 1);
    }
    
    return nextFourAM;
  };

  // Load questions from cache or fetch new ones
  useEffect(() => {
    const loadQuestions = async () => {
      // Fetch questions (backend handles caching)
      await fetchQuestions();
      
      // Set next update time
      setNextUpdateTime(getNextFourAMIST());
    };

    loadQuestions();
    fetchPreviousQuestions();
  }, []);

  const fetchPreviousQuestions = async () => {
    try {
      setLoadingPrevious(true);
      
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';
      const baseUrl = apiUrl.replace('/api/leaderboard', '');
      
      console.log('Fetching previous questions from:', `${baseUrl}/api/exam/previous-questions`);
      
      const response = await axios.get(`${baseUrl}/api/exam/previous-questions`);
      
      console.log('Previous questions response:', response.data);
      
      if (response.data.success && response.data.previousQuestions.length > 0) {
        setPreviousQuestions(response.data.previousQuestions);
        // Auto-select the first (most recent) date
        setSelectedDate(0);
      } else {
        console.log('No previous questions found');
      }
    } catch (err) {
      console.error('Error fetching previous questions:', err);
    } finally {
      setLoadingPrevious(false);
    }
  };

  const fetchQuestions = async () => {
    try {
      setLoading(true);
      setError(null);
      
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5000';
      const baseUrl = apiUrl.replace('/api/leaderboard', '');
      
      const response = await axios.get(`${baseUrl}/api/exam/generate-questions`);
      
      if (response.data.success) {
        const newQuestions = response.data.questions;
        const timestamp = response.data.generatedAt;
        const fromCache = response.data.fromCache || false;
        
        // Cache the questions
        localStorage.setItem('examQuestions', JSON.stringify({
          questions: newQuestions,
          timestamp: timestamp
        }));
        
        setQuestions(newQuestions);
        setGeneratedAt(new Date(timestamp));
        setIsFromCache(fromCache);
        
        console.log(fromCache ? '✅ Loaded from database cache' : '🆕 Freshly generated questions');
      } else {
        setError('Failed to fetch questions');
      }
    } catch (err) {
      console.error('Error fetching questions:', err);
      setError('Unable to load questions. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  const getDifficultyColor = (difficulty) => {
    switch(difficulty) {
      case "Easy": return "text-green-400 bg-green-500/20 border-green-500/30";
      case "Medium": return "text-yellow-400 bg-yellow-500/20 border-yellow-500/30";
      case "Hard": return "text-red-400 bg-red-500/20 border-red-500/30";
      default: return "text-gray-400 bg-gray-500/20 border-gray-500/30";
    }
  };

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-6">
        <h1 className="text-4xl font-bold text-white mb-2 bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
          Practice Problem
        </h1>
        <p className="text-gray-400 text-sm">{today}</p>
      </div>

      <div className="bg-gradient-to-br from-blue-600/20 to-purple-600/20 backdrop-blur-md p-6 rounded-lg border border-blue-500/30 mb-6">
        <div className="flex items-center justify-between">
          <div className="flex-1">
            <h2 className="text-xl font-semibold text-white mb-2"> Daily Practice</h2>
            <p className="text-gray-300 mb-2">
              Fresh LeetCode problems generated by AI every day at 12:00 AM IST
            </p>
            <div className="flex flex-col gap-1 text-sm">
              {generatedAt && (
                <p className="text-gray-400 flex items-center gap-2">
                   Today's questions generated at: {new Date(generatedAt).toLocaleString('en-IN', {
                    timeZone: 'Asia/Kolkata',
                    hour: '2-digit',
                    minute: '2-digit',
                    hour12: true
                  })} IST
                  {isFromCache && (
                    <span className="px-2 py-0.5 bg-green-500/20 text-green-300 rounded text-xs border border-green-500/30">
                      ✓ Same questions until 12AM
                    </span>
                  )}
                </p>
              )}
              {nextUpdateTime && (
                <p className="text-blue-300">
                   Next update: {nextUpdateTime.toLocaleString('en-IN', {
                    timeZone: 'Asia/Kolkata',
                    month: 'short',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                    hour12: true
                  })} IST (Tomorrow at 12:00 AM)
                </p>
              )}
            </div>
          </div>
        </div>
      </div>

      {error && (
        <div className="bg-red-500/20 backdrop-blur-md p-4 rounded-lg border border-red-500/30 mb-6">
          <p className="text-red-300 flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            {error}
          </p>
        </div>
      )}

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="text-center">
            <svg className="animate-spin h-12 w-12 mx-auto mb-4 text-blue-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            <p className="text-gray-300">AI is generating your practice questions...</p>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {questions.map((question, index) => (
            <div 
              key={index}
              className="bg-gray-800/50 backdrop-blur-md p-6 rounded-lg border border-gray-700/40 hover:border-blue-500/50 transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/10"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-xl font-semibold text-white">
                      {question.questionNumber}. {question.questionName}
                    </h3>
                    <span className={`px-3 py-1 rounded-full text-xs font-medium border ${getDifficultyColor(question.questionLevel)}`}>
                      {question.questionLevel}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="px-2 py-1 bg-blue-500/20 text-blue-300 rounded text-xs border border-blue-500/30">
                      LeetCode #{question.questionNumber}
                    </span>
                    <span className="px-2 py-1 bg-purple-500/20 text-purple-300 rounded text-xs border border-purple-500/30">
                      AI Generated
                    </span>
                  </div>
                </div>
              </div>
              <a 
                href={question.questionLink}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-lg hover:from-blue-600 hover:to-purple-700 transition-all duration-300 font-medium"
              >
                Solve on LeetCode
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                </svg>
              </a>
            </div>
          ))}
        </div>
      )}

      <div className="mt-8 bg-gray-800/50 backdrop-blur-md p-6 rounded-lg border border-gray-700/40">
        <h3 className="text-lg font-semibold text-white mb-3">💡 Tips for Success</h3>
        <ul className="space-y-2 text-gray-300">
          <li className="flex items-start gap-2">
            <span className="text-blue-400 mt-1">•</span>
            <span>Start with Easy problems and gradually move to Medium and Hard</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-400 mt-1">•</span>
            <span>Focus on understanding the problem before coding</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-400 mt-1">•</span>
            <span>Practice time management - aim to solve each problem within 30-45 minutes</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="text-blue-400 mt-1">•</span>
            <span>New questions are automatically generated daily at 12:00 AM IST</span>
          </li>
        </ul>
      </div>

      {/* Previous Days' Questions Section - Calendar Style */}
      <div className="mt-8">
        <h2 className="text-2xl font-bold text-white mb-4 bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
           Previous Days' Questions
        </h2>
        
        {loadingPrevious ? (
          <div className="bg-gray-800/50 backdrop-blur-md p-6 rounded-lg border border-gray-700/40">
            <p className="text-gray-400 text-center">Loading previous questions...</p>
          </div>
        ) : previousQuestions.length === 0 ? (
          <div className="bg-gray-800/50 backdrop-blur-md p-6 rounded-lg border border-gray-700/40">
            <p className="text-gray-400 text-center">No previous questions available yet.</p>
          </div>
        ) : (
          <div className="bg-gray-800/50 backdrop-blur-md rounded-lg border border-gray-700/40 overflow-hidden">
            {/* Calendar Date Row */}
            <div className="p-4 border-b border-gray-700/40 bg-gray-900/30">
              <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-thin scrollbar-thumb-purple-500 scrollbar-track-gray-700">
                {previousQuestions.map((dayData, index) => {
                  const questionDate = new Date(dayData.date);
                  const dateNum = questionDate.getDate();
                  const monthShort = questionDate.toLocaleDateString('en-US', { month: 'short' });
                  const isSelected = selectedDate === index;
                  
                  return (
                    <button
                      key={index}
                      onClick={() => setSelectedDate(index)}
                      className={`flex-shrink-0 flex flex-col items-center justify-center w-16 h-20 rounded-lg border-2 transition-all duration-300 ${
                        isSelected
                          ? 'bg-gradient-to-br from-purple-500 to-pink-600 border-purple-400 shadow-lg shadow-purple-500/50'
                          : 'bg-gray-700/50 border-gray-600/30 hover:border-purple-500/50 hover:bg-gray-700'
                      }`}
                    >
                      <span className={`text-2xl font-bold ${isSelected ? 'text-white' : 'text-gray-300'}`}>
                        {dateNum}
                      </span>
                      <span className={`text-xs ${isSelected ? 'text-white' : 'text-gray-400'}`}>
                        {monthShort}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Selected Date Questions */}
            {selectedDate !== null && previousQuestions[selectedDate] && (
              <div className="p-6">
                <div className="mb-4">
                  <h3 className="text-xl font-semibold text-white mb-1">
                    {new Date(previousQuestions[selectedDate].date).toLocaleDateString('en-US', {
                      weekday: 'long',
                      month: 'long',
                      day: 'numeric',
                      year: 'numeric'
                    })}
                  </h3>
                  <p className="text-sm text-gray-400">
                    {previousQuestions[selectedDate].questions.length} questions
                  </p>
                </div>

                <div className="space-y-3">
                  {previousQuestions[selectedDate].questions.map((question, qIndex) => (
                    <div
                      key={qIndex}
                      className="bg-gray-900/50 p-4 rounded-lg border border-gray-600/30 hover:border-purple-500/50 transition-all duration-300"
                    >
                      <div className="flex items-center gap-3 mb-2">
                        <h4 className="text-base font-semibold text-white flex-1">
                          {question.questionNumber}. {question.questionName}
                        </h4>
                        <span className={`px-2 py-1 rounded-full text-xs font-medium border ${getDifficultyColor(question.questionLevel)}`}>
                          {question.questionLevel}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="px-2 py-1 bg-blue-500/20 text-blue-300 rounded text-xs border border-blue-500/30">
                          LeetCode #{question.questionNumber}
                        </span>
                        <a
                          href={question.questionLink}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="ml-auto inline-flex items-center gap-1 px-3 py-1 bg-gradient-to-r from-purple-500 to-pink-600 text-white rounded-md hover:from-purple-600 hover:to-pink-700 transition-all duration-300 text-sm font-medium"
                        >
                          Solve
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                          </svg>
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* No Date Selected Message */}
            {selectedDate === null && (
              <div className="p-6 text-center">
                <p className="text-gray-400">👆 Click on a date to view questions</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default Exam;

